version: '3.5'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c 'if [ "$ENVIRONMENT" = "production" ]; then echo "Running in production environment" && [ "npm", "run", "start:prod" ]; else echo "Running in development environment" && [ "npm", "run", "start:dev" ]; fi'
    container_name: nest
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
