version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_HOST: db
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:debug
    container_name: nest
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - '.:/app'
      - './node_modules:/app/node_modules'
